---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: my-quiz-strip-prefix
  namespace: my-quiz-namespace
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-quiz-ingress
  namespace: my-quiz-namespace
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: my-quiz-namespace-my-quiz-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-quiz-ui
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-quiz-api
            port:
              number: 5000
