apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: my-quiz-namespace
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/postgresql/data